Repository URECA-UFit/ufit-llm, pull requests merged in 2025-06, with the labels that each got.

#20 Feat: 유저 정보 추출
  requirements.txt
  ufit/database/database.py
  ufit/dto/user_info.py
  ufit/models/chat_room.py
  ufit/models/chatbot.py
  ufit/models/mobile_device.py
  ufit/models/rate_plan.py
  ufit/models/time_base.py
  ufit/models/usages.py
  ufit/models/user.py
  ufit/routes/recommend_routes.py
  ufit/services/recommend_service.py
  ufit/services/user_service.py
Labels: feat

#23 feat: 챗봇 리뷰 시 회원 질의 요약
  requirements.txt
  ufit/routes/chat.py
  ufit/services/chat_bot_review_user_query.py
Labels: feat

#26 Feat: llm 답변 생성
  requirements.txt
  ufit/database/database.py
  ufit/routes/recommend_routes.py
  ufit/services/llm_answer_agent.py
  ufit/services/recommend_service.py
  ufit/services/recommend_service_hj.py
  ufit/tests/llm_ban_test.py
  ufit/tests/llm_branch_test.py
  ufit/tests/llm_speech_test.py
Labels: feat

#30 Fix: 비회원 챗봇 답변 추가
  ufit/database/database.py
  ufit/dto/recommend.py
  ufit/routes/recommend_routes.py
  ufit/services/user_service.py
Labels: fix

#36 [Feat] embedding exception 추가
  ufit/exceptions/__init__.py
  ufit/exceptions/embedding_exception.py
  ufit/routes/rateplan_routes.py
  ufit/services/embedding_service.py
  ufit/tests/test_rateplan_routes.py
Labels: feat

#41 fix: 요금제 ID 타입 수정
  ufit/dto/user_info.py
  ufit/models/rate_plan.py
  ufit/services/recommend_service.py
  ufit/services/user_service.py
Labels: fix

#44 fix: default_factory에 lamba를 사용하도록 변경
  ufit/models/rate_plan.py
Labels: fix

#46 Fea: 프롬프트 엔지니어링 성능 개선
  requirements.txt
  ufit/data/plans.json
  ufit/llm/ai_model.py
  ufit/llm/history.py
  ufit/llm/ufit_graph.py
  ufit/llm/ufit_graph_prompt.py
  ufit/models/chat_room.py
  ufit/models/chatbot.py
  ufit/models/rate_plan.py
  ufit/routes/recommend_routes.py
  ufit/services/embedding.py
  ufit/services/recommend_service.py
  ufit/services/user_service.py
  ufit/tests/llm_branch_test.py
Labels: feat, refactor

#53 Fix: 금칙어 필터링 추가
  ufit/llm/ufit_graph.py
  ufit/llm/ufit_graph_prompt.py
  ufit/services/user_service.py
Labels: fix, feat

#61 fix: RatePlan Model 필드를 Optional으로 변경
  ufit/data/plans_0619.json
  ufit/models/rate_plan.py
Labels: fix

#67 Feat: 임베딩 메타데이터 추가
  ufit/llm/history_aware_retriever.py
  ufit/llm/llm_model.py
  ufit/llm/ufit_graph.py
  ufit/llm/ufit_graph_prompt.py
  ufit/models/rate_plan.py
  ufit/services/embedding.py
  ufit/services/recommend_service.py
  ufit/services/user_service.py
Labels: feat

#69 fix: ordercarrier prompt 수정
  ufit/llm/ufit_graph.py
  ufit/llm/ufit_prompt.py
Labels: fix

#72 fix: 타통신사 판별 프롬프트 수정
  ufit/llm/ufit_prompt.py
Labels: fix

#76 chore: 배포
  ufit/llm/ufit_prompt.py
  ufit/services/embedding_service.py
Labels: chore

#78 Feat: 사용자의 통신 성향을 분석하여 요금제를 추천
  ufit/dto/user_info.py
  ufit/llm/ufit_graph.py
  ufit/llm/ufit_prompt.py
  ufit/services/llm_answer_agent.py
  ufit/services/recommend_service.py
  ufit/services/user_service.py
  ufit/tests/llm_ban_test.py
  ufit/tests/llm_speech_test.py
Labels: fix, feat

#82 feat: 요금제 추천 시 현재 사용중인 요금제와 비교해주는 기능 추가
  ufit/llm/ufit_prompt.py
  ufit/services/user_service.py
Labels: feat

#84 chore: 주석 제거
  ufit/database/database.py
  ufit/llm/ufit_graph.py
  ufit/llm/ufit_prompt.py
  ufit/routes/chat.py
  ufit/routes/recommend_routes.py
  ufit/services/chat_bot_review_user_query.py
  ufit/services/chat_service.py
  ufit/services/embedding.py
  ufit/services/embedding_service.py
  ufit/services/formatter.py
  ufit/services/recommend_service.py
  ufit/services/sync_embedding.py
  ufit/services/user_service.py
Labels: chore
